name: pull_request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - node: 14
          - node: 16
          - node: 18
    name: Node.js ${{ matrix.version.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
