name: pull_request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - node: 4
          - node: 6
          - node: 8
          - node: 12
          - node: 10
          - node: 14
          - node: 16
          - node: 18
          - node: 20
    name: Node.js ${{ matrix.version.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Test
        run: npm test
      - name: Report
        run: npx c8 report --reporter=text-lcov > coverage/lcov.info
      - name: Coverage
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
